gpus: 1
distributed_backend: ddp
seed: 0
max_epochs: 100

image_net_path: ???
img_size: 32
batch_size: 128
data_augmentation: false
n_validation_examples: 32
beta: 5

z_size: 128
ae_size: 1024

gensim_model_path: ???
word_embeddings: null

dataloader:
  num_workers: 0

optim:
  lr: 1e-4
  weight_decay: 3e-5

scheduler:
  step: 20
  gamma: 0.5

neptune:
  project_name: null
  api_token: null
  mode: async
  resume: null

checkpoints_dir: ???
resume_from_checkpoint: null
