gpus: 1
distributed_backend: ddp
seed: 0
max_epochs: 100

image_net_path: ???
cifar10_path: ???
simple_shapes_path: ???

visual_dataset: "imagenet"

img_size: 32

n_validation_examples: 32

global_workspace:
  monitor_grad_norms: false  # if true, training is a bit slower.
  batch_size: 1024
  data_augmentation: true

  z_size: 512
  hidden_size: 512
  prop_labelled_images: 1.  # of the allowed classes to be labelled.
  classes_labelled_images: null  # null is all classes
  vae_checkpoint: ???
  cycle_loss_fn: "mse"
  supervision_loss_fn: {  # available: "mse", "cosine", "cross_entropy"
    "v": "mse",
    "t": "mse"
  }

  optim:
    lr: 1e-4
    discriminator_lr: 5e-5
    weight_decay: 3e-5

  scheduler:
    step: 20
    gamma: 0.5

vae:
  batch_size: 1024
  data_augmentation: false

  beta: 0.5
  z_size: 256
  ae_size: 1024

  n_FID_samples: 1000

  optim:
    lr: 1e-4
    weight_decay: 3e-5

  scheduler:
    step: 20
    gamma: 0.5


losses:
  coefs:
    demi_cycles: 1.
    cycles: 1.
    supervision: 1.

gensim_model_path: ???
word_embeddings: null

dataloader:
  num_workers: 0

neptune:
  project_name: null
  api_token: null
  mode: async
  resume: null

checkpoints_dir: ???
resume_from_checkpoint: null
