gpus: 1
distributed_backend: ddp
seed: 0
max_epochs: 100

image_net_path: ???
img_size: 32
batch_size: 32
n_validation_examples: 32
beta: 1

z_size: 128


dataloader:
  num_workers: 0

optim:
  lr: 1e-3
  weight_decay: 5e-4

scheduler:
  step: 20
  gamma: 0.5

neptune:
  project_name: null
  api_token: null
  mode: async

checkpoints_dir: ???
resume_from_checkpoint: null
