from bim_gw.modules.domain_modules.simple_shapes.downstream.unpaired_classifier_attributes import \
    UnpairedClassifierAttributes
from bim_gw.modules.domain_modules.simple_shapes.downstream.unpaired_classifier_text import UnpairedClassifierText
